
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # or the version you're using
    hooks: []
      #- id: trailing-whitespace
      #- id: end-of-file-fixer
      #  exclude: ^.vscode/
      #- id: check-yaml
      #- id: check-added-large-files

  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a7 # Use the appropriate tag from the pylint repository
    hooks: []
      #- id: pylint
      #  language_version: python3.13
      #  additional_dependencies: [pylint]
      #  exclude: ^tests/
      #  args: ["--fail-under=5.0"]
